import streamlit as st
import requests

# 1. Page Configuration & Styling
st.set_page_config(page_title="AI Grant & Funding Finder", page_icon="💼", layout="centered")

st.title("💼 AI Grant & Funding Finder Dashboard")
st.markdown("---")
st.subheader("Enter Startup Profile Parameters")

# 2. Frontend Input Fields
col1, col2 = st.columns(2)

with col1:
    company_name = st.text_input("Company Name", placeholder="e.g., TECH achivers")
    domain = st.text_input("Industry Domain", placeholder="e.g., Ai driven")
    location = st.text_input("Location", placeholder="e.g., Pune")

with col2:
    stage = st.selectbox("Current Stage", ["Idea / Concept", "Prototype / MVP built", "Early Traction", "Scaling"])
    target_funding = st.number_input("Target Funding (INR)", min_value=0, step=50000, value=5000000)

st.markdown("---")

# 3. Inline validation engine (IBM Bob Engine Emulator)
def validate_proposal(proposal_text: str) -> dict:
    """
    Validates proposal structure and returns compliance status.
    """
    if "# Executive Summary" in proposal_text or "Evaluation Report" in proposal_text:
        return {"status": "Verified: Layout Compliance Passed", "code": 200}
    else:
        return {"status": "Warning: Formatting Anomalies Detected", "code": 422}

# 4. Submission Logic
if st.button("Evaluate & Route to IBM Bob", type="primary"):
    if not company_name or not domain or not location:
        st.error("Please fill out all input fields before submitting.")
    else:
        with st.spinner("🤖 Connecting to deployed watsonx agent to compile full blueprint..."):
            
            # Formulate the prompt using the user's inputs
            user_prompt = f"Evaluate {company_name} in the {domain} industry based in {location} with target funding of {target_funding} INR."
            
            # Fetch backend credentials securely from Streamlit Cloud Secrets Environment
            try:
                bearer_token = st.secrets["WATSONX_API_KEY"]
                watsonx_url = st.secrets["WATSONX_URL"]
            except KeyError:
                st.error("Missing API configuration secrets. Please configure WATSONX_API_KEY and WATSONX_URL in your Streamlit dashboard settings.")
                st.stop()
                
            headers = {
                "Authorization": f"Bearer {bearer_token}",
                "Content-Type": "application/json"
            }
            payload = {
                "message": user_prompt
            }
            
            try:
                # Step A: Send user parameters directly to your live deployed cloud agent
                response = requests.post(watsonx_url, json=payload, headers=headers, timeout=30)
                
                if response.status_code == 200:
                    # Step B: Extract the rich long text response generated by watsonx
                    watsonx_generated_text = response.json().get("output", "")
                    
                    st.success("🎉 watsonx Agent Generation Complete!")
                    
                    # Step C: Send the text block into our Bob Engine validation rules block
                    compliance_data = validate_proposal(watsonx_generated_text)
                    
                    if compliance_data["code"] == 200:
                        st.info(f"**Backend Orchestration Engine Status:** {compliance_data.get('status')}")
                        
                        st.markdown("---")
                        # Step D: Render the complete long text block beautifully onto the webpage
                        st.subheader("📊 Full Generated Evaluation Blueprint")
                        st.markdown(watsonx_generated_text)
                        
                    else:
                        st.warning(f"**Engine Status:** {compliance_data.get('status')}")
                        st.markdown(watsonx_generated_text)
                else:
                    st.error(f"Failed to fetch from watsonx. Status Code: {response.status_code}")
                    st.caption(response.text)
                    
            except requests.exceptions.RequestException as e:
                st.error(f"Connection Error: Could not reach watsonx cloud servers. Details: {e}")