import streamlit as st
import requests

# 1. Page Configuration & Styling
st.set_page_config(page_title="AI Grant & Funding Finder", page_icon="💼", layout="centered")

st.title("💼 AI Grant & Funding Finder Dashboard")
st.markdown("---")

# Sidebar for Enterprise Credentials (Keeps your code clean and secure)
st.sidebar.header("🔑 IBM watsonx Configuration")
watsonx_url = st.sidebar.text_input(
    "watsonx API Endpoint URL", 
    value="https://us-south.watson-orchestrate.cloud.ibm.com/v1/orchestrate/agents/YOUR_AGENT_ID/chat/completions",
    type="default"
)
bearer_token = st.sidebar.text_input("Watsonx API Key / Bearer Token", type="password")

st.subheader("Enter Startup Profile Parameters")

# 2. Frontend Input Fields
col1, col2 = st.columns(2)

with col1:
    company_name = st.text_input("Company Name", placeholder="e.g., TECH achivers")
    domain = st.text_input("Industry Domain", placeholder="e.g., Ai driven")
    location = st.text_input("Location", placeholder="e.g., Pune")

with col2:
    stage = st.selectbox("Current Stage", ["Idea / Concept", "Prototype / MVP built", "Early Traction", "Scaling"])
    target_funding = st.number_input("Target Funding (INR)", min_value=0, step=50000, value=5000000)

st.markdown("---")

# 3. Inline validation engine (IBM Bob Engine Emulator)
def validate_proposal(proposal_text: str) -> dict:
    """
    Validates proposal structure and returns compliance status.
    """
    if "# Executive Summary" in proposal_text or "Evaluation Report" in proposal_text:
        return {"status": "Verified: Layout Compliance Passed", "code": 200}
    else:
        return {"status": "Warning: Formatting Anomalies Detected", "code": 422}

# 4. Submission Logic
if st.button("Evaluate & Route to IBM Bob", type="primary"):
    if not company_name or not domain or not location:
        st.error("Please fill out all input fields before submitting.")
    elif not bearer_token:
        st.error("Please enter your watsonx API Key/Token in the sidebar to connect to the cloud agent.")
    else:
        # STEP A: Call Deployed watsonx Agent to get the long text
        with st.spinner("🤖 Connecting to deployed watsonx agent to compile full blueprint..."):
            
            user_prompt = f"Evaluate {company_name} in the {domain} industry based in {location} with target funding of {target_funding} INR."
            
            headers = {
                "Authorization": f"Bearer {bearer_token}",
                "Content-Type": "application/json"
            }
            payload = {
                "message": user_prompt
            }
            
            try:
                # Fire the request to your live deployed watsonx agent
                response = requests.post(watsonx_url, json=payload, headers=headers, timeout=30)
                
                if response.status_code == 200:
                    # Extract the full text generated by your custom instructions/rubric
                    watsonx_generated_text = response.json().get("output", "")
                    
                    st.success("🎉 watsonx Agent Generation Complete!")
                    
                    # STEP B: Run the verification check on the returned long text
                    compliance_data = validate_proposal(watsonx_generated_text)
                    
                    if compliance_data["code"] == 200:
                        st.info(f"**Backend Orchestration Engine Status:** {compliance_data.get('status')}")
                        
                        st.markdown("---")
                        # STEP C: Display the long text directly on the frontend UI
                        st.subheader("📊 Full Generated Evaluation Blueprint")
                        st.markdown(watsonx_generated_text)
                        
                    else:
                        st.warning(f"**Engine Status:** {compliance_data.get('status')}")
                        st.markdown(watsonx_generated_text)
                else:
                    st.error(f"Failed to fetch from watsonx. Status Code: {response.status_code}")
                    st.caption(response.text)
                    
            except requests.exceptions.RequestException as e:
                st.error(f"Connection Error: Could not reach watsonx servers. Details: {e}")